package me.villagerunknown.platform.util;

import java.util.*;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.npc.villager.VillagerProfession;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.structure.Structure;

public class ListUtil {
	
	public static List<String> PLAYER_NAMES = List.of(
			"VillagerUnknown"
	);
	
	public static List<String> HUMAN_NAMES = List.of(
			"Abigail",
			"Adrian",
			"Aisha",
			"Alden",
			"Alec",
			"Alex",
			"Alexander",
			"Alexandrea",
			"Alice",
			"Alina",
			"Alison",
			"Alistair",
			"Amelia",
			"Ansel",
			"Anthony",
			"Andrea",
			"Andrew",
			"Andy",
			"Angela",
			"Angelo",
			"Ani",
			"Anna",
			"Annabelle",
			"Annika",
			"Anya",
			"Arden",
			"Ariana",
			"Arielle",
			"Ashley",
			"Asher",
			"Astrid",
			"Austin",
			"Ava",
			"Ayisha",
			"Beatrix",
			"Beau",
			"Ben",
			"Benajmin",
			"Bennett",
			"Bianca",
			"Blaine",
			"Blaise",
			"Brandon",
			"Brayden",
			"Brenda",
			"Brenna",
			"Briony",
			"Briella",
			"Brooke",
			"Bryce",
			"Caius",
			"Caleb",
			"Callie",
			"Callum",
			"Camille",
			"Candace",
			"Cara",
			"Carla",
			"Carlee",
			"Carly",
			"Carmen",
			"Carson",
			"Cassandra",
			"Cassian",
			"Catherine",
			"Cecilia",
			"Cedric",
			"Charles",
			"Charlie",
			"Chloe",
			"Clara",
			"Claudia",
			"Cleo",
			"Collin",
			"Connor",
			"Corwin",
			"Courtney",
			"Dahlia",
			"Daisy",
			"Daniel",
			"Daniella",
			"Daphne",
			"Darcy",
			"David",
			"Dean",
			"Delilah",
			"Desmond",
			"Derek",
			"Dominic",
			"Dorian",
			"Drew",
			"Drufus",
			"Dylan",
			"Eamon",
			"Eddie",
			"Ed",
			"Eduardo",
			"Edward",
			"Elena",
			"Eleanor",
			"Elias",
			"Eliza",
			"Elowen",
			"Elyse",
			"Ember",
			"Emerson",
			"Emilia",
			"Emmett",
			"Eric",
			"Erin",
			"Esme",
			"Ethan",
			"Etta",
			"Eugene",
			"Evelyn",
			"Evie",
			"Ezra",
			"Felix",
			"Fenric",
			"Ferdinand",
			"Fern",
			"Fiona",
			"Finn",
			"Florence",
			"Foxy",
			"Frederick",
			"Freya",
			"Galadriel",
			"Gareth",
			"Gavin",
			"Geoff",
			"Geoffrey",
			"Gideon",
			"Giselle",
			"Gracie",
			"Grayson",
			"Griffin",
			"Gwen",
			"Hallie",
			"Hannah",
			"Harlen",
			"Harley",
			"Harlow",
			"Harold",
			"Harry",
			"Hazel",
			"Henry",
			"Holden",
			"Holly",
			"Hugo",
			"Ian",
			"Ines",
			"Irene",
			"Isla",
			"Isolde",
			"Ivan",
			"Ivy",
			"Jack",
			"Jacob",
			"James",
			"Jan",
			"Jannifer",
			"Jared",
			"Jasmine",
			"Jason",
			"Jeff",
			"Jeffrey",
			"Jen",
			"Jenna",
			"Jennifer",
			"Jin",
			"Jinnifer",
			"Jocelyn",
			"Joe",
			"John",
			"Jonas",
			"Jonathan",
			"Jonny",
			"Jordan",
			"Jorvik",
			"Joseph",
			"Joshua",
			"Josie",
			"Jude",
			"Judah",
			"Julia",
			"Julian",
			"June",
			"Justin",
			"Kaelen",
			"Kai",
			"Kaleb",
			"Kara",
			"Karen",
			"Karina",
			"Karl",
			"Kayla",
			"Kevin",
			"Kian",
			"Kira",
			"Kyle",
			"Lara",
			"Laura",
			"Lauren",
			"Leah",
			"Leif",
			"Lena",
			"Leo",
			"Leonard",
			"Leslie",
			"Lewis",
			"Liam",
			"Lila",
			"Lilith",
			"Lily",
			"Linda",
			"Lindsay",
			"Liora",
			"Logan",
			"Louis",
			"Lucy",
			"Luis",
			"Luke",
			"Lyle",
			"Maeve",
			"Maggie",
			"Madeline",
			"Marcus",
			"Marcy",
			"Margot",
			"Maria",
			"Mark",
			"Marshall",
			"Martin",
			"Mary",
			"Matilda",
			"Matt",
			"Matthew",
			"Matthius",
			"Maya",
			"Megan",
			"Melanie",
			"Melissa",
			"Merrick",
			"Michael",
			"Milo",
			"Mira",
			"Miranda",
			"Mitchell",
			"Morgan",
			"Naomi",
			"Nash",
			"Nathan",
			"Nerissa",
			"Nico",
			"Nicholas",
			"Nikki",
			"Nina",
			"Nikola",
			"Noah",
			"Nora",
			"Oberon",
			"Oliver",
			"Ollie",
			"Olivia",
			"Olwen",
			"Opal",
			"Orion",
			"Oswald",
			"Owen",
			"Paige",
			"Patrick",
			"Pearl",
			"Peregrine",
			"Phaedra",
			"Phoebe",
			"Quentin",
			"Quinn",
			"Rachel",
			"Rebecca",
			"Ren",
			"Rennifer",
			"Rhiannon",
			"Riley",
			"Robert",
			"Ronan",
			"Rose",
			"Ruby",
			"Ryan",
			"Sable",
			"Samuel",
			"Sara",
			"Sarah",
			"Sasha",
			"Savannah",
			"Scott",
			"Sebastian",
			"Serena",
			"Shawn",
			"Sophia",
			"Sophie",
			"Stella",
			"Steve",
			"Steven",
			"Summer",
			"Sylvan",
			"Sybil",
			"Talon",
			"Tamsin",
			"Tara",
			"Ted",
			"Thea",
			"Theo",
			"Thomas",
			"Toby",
			"Tristan",
			"Tyler",
			"Ulric",
			"Valerie",
			"Vera",
			"Vesper",
			"Victoria",
			"Violet",
			"Vivian",
			"Viveka",
			"Walter",
			"Wayne",
			"Wesley",
			"Whitney",
			"Wilma",
			"Wilson",
			"Wren",
			"Wynne",
			"Xander",
			"Xandra",
			"Xavier",
			"Yara",
			"Ysolde",
			"Yvonne",
			"Zane",
			"Zara",
			"Zeke",
			"Zephyr",
			"Zoe"
	);
	
	public static List<String> CAT_NAMES = List.of(
			"Nikola",
			"Fluffy",
			"Orion",
			"Rabbit",
			"Oliver",
			"Daisy",
			"Jasper",
			"Bella",
			"Felix",
			"Luna",
			"Chloe",
			"Leo",
			"Willow",
			"Sebastian",
			"Snickers",
			"Niblet",
			"Pudding",
			"Jellybean",
			"Bubbles",
			"Whiskers",
			"Tater Tot",
			"Peaches",
			"Poppy",
			"Sprout",
			"Nimbus",
			"Quibble",
			"Zephyr",
			"Sprocket",
			"Munchkin",
			"Tofu",
			"Tango",
			"Waffle",
			"Gizmo",
			"Jinxy",
			"Willow",
			"Aspen",
			"Maple",
			"Storm",
			"Sage",
			"River",
			"Luna",
			"Ocean",
			"Poppy",
			"Merlin",
			"Artemis",
			"Thor",
			"Pixie",
			"Loki",
			"Phoenix",
			"Zelda",
			"Willow",
			"Gandalf",
			"Freya"
	);
	
	public static List<String> DOG_NAMES = List.of(
			"Rover",
			"Ralph",
			"Chase",
			"Diesel",
			"Shadow",
			"Raven",
			"Rocky",
			"Hunter",
			"Rebel",
			"Fang",
			"Rogue",
			"Bandit",
			"Thor",
			"Max",
			"Bella",
			"Charlie",
			"Daisy",
			"Duke",
			"Lucy",
			"Rex",
			"Sadie",
			"Sampson",
			"Molly",
			"Biscuit",
			"Peanut",
			"Poppy",
			"Noodle",
			"Tater Tot",
			"Waffles",
			"Sprout",
			"Snickers",
			"Cupcake",
			"Bubbles",
			"Ziggy",
			"Mochi",
			"Sprocket",
			"Widget",
			"Pickles",
			"Tofu",
			"Munchkin",
			"Pudding",
			"Hubble",
			"River",
			"Aspen",
			"Willow",
			"Cedar",
			"Maple",
			"Storm",
			"Ocean",
			"Daisy",
			"Sky",
			"Rocky"
	);
	
	public static List<String> BIRD_NAMES = List.of(
			"Crackers",
			"Clinger",
			"Tori",
			"Kiwi",
			"Apollo",
			"Luna",
			"Ruby",
			"Merlin",
			"Oliver",
			"Bella",
			"Gatsby",
			"Sage",
			"Willow",
			"Twinkie",
			"Twinkle",
			"Pippin",
			"Peep",
			"Snickers",
			"Waffle",
			"Fuzz",
			"Popcorn",
			"Biscuit",
			"Niblet",
			"Bubbles",
			"Sky",
			"Cloud",
			"Aspen",
			"Storm",
			"Coral",
			"Pine",
			"Ember",
			"Breeze",
			"Meadow",
			"Pebble",
			"Phoenix",
			"Zephyr",
			"Merlin",
			"Freya",
			"Thor",
			"Lyra",
			"Valkyrie",
			"Willow",
			"Griffin",
			"Snappy",
			"Bitey",
			"Zuzu",
			"Noodle",
			"Tofu",
			"Wiggly",
			"Doodle",
			"Jinxy",
			"Sprocket",
			"Ziggy",
			"Gizmo",
			"Pickles",
			"Pepper",
			"Mango",
			"Cookie",
			"Coconut",
			"Squawk",
			"Squelch",
			"Chatter",
			"Chitter",
			"Tango",
			"Pesto",
			"Sapphire",
			"Ruby",
			"Topaz",
			"Emerald",
			"Indigo",
			"Opal",
			"Onyx",
			"Pearl",
			"Goldie",
			"Pesky Bird"
	);
	
	public static List<VillagerProfession> VILLAGER_PROFESSIONS = List.of(
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.ARMORER)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.BUTCHER)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.CARTOGRAPHER)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.CLERIC)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.FARMER)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.FISHERMAN)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.FLETCHER)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.LEATHERWORKER)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.LIBRARIAN)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.MASON)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.NITWIT)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.SHEPHERD)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.TOOLSMITH)),
			Objects.requireNonNull(BuiltInRegistries.VILLAGER_PROFESSION.getValue(VillagerProfession.WEAPONSMITH))
	);
	
	public static List<String> VILLAGER_PROFESSION_STRINGS = new ArrayList<String>(){{
		add( VillagerProfession.ARMORER.identifier().getPath().toLowerCase() );
		add( VillagerProfession.BUTCHER.identifier().getPath().toLowerCase() );
		add( VillagerProfession.CARTOGRAPHER.identifier().getPath().toLowerCase() );
		add( VillagerProfession.CLERIC.identifier().getPath().toLowerCase() );
		add( VillagerProfession.FARMER.identifier().getPath().toLowerCase() );
		add( VillagerProfession.FISHERMAN.identifier().getPath().toLowerCase() );
		add( VillagerProfession.FLETCHER.identifier().getPath().toLowerCase() );
		add( VillagerProfession.LEATHERWORKER.identifier().getPath().toLowerCase() );
		add( VillagerProfession.LIBRARIAN.identifier().getPath().toLowerCase() );
		add( VillagerProfession.MASON.identifier().getPath().toLowerCase() );
		add( VillagerProfession.NITWIT.identifier().getPath().toLowerCase() );
		add( VillagerProfession.SHEPHERD.identifier().getPath().toLowerCase() );
		add( VillagerProfession.TOOLSMITH.identifier().getPath().toLowerCase() );
		add( VillagerProfession.WEAPONSMITH.identifier().getPath().toLowerCase() );
	}};
	
	public static final List<Block> BEDS = List.of(
			Blocks.BED.black(),
			Blocks.BED.blue(),
			Blocks.BED.brown(),
			Blocks.BED.cyan(),
			Blocks.BED.gray(),
			Blocks.BED.green(),
			Blocks.BED.lightBlue(),
			Blocks.BED.lightGray(),
			Blocks.BED.lime(),
			Blocks.BED.magenta(),
			Blocks.BED.orange(),
			Blocks.BED.pink(),
			Blocks.BED.purple(),
			Blocks.BED.red(),
			Blocks.BED.white(),
			Blocks.BED.yellow()
	);
	
	public static List<Block> FLAME_SOURCE_BLOCKS = List.of(
			Blocks.LAVA,
			Blocks.FIRE,
			Blocks.CAMPFIRE,
			Blocks.TORCH,
			Blocks.WALL_TORCH,
			Blocks.LAVA_CAULDRON,
			Blocks.JACK_O_LANTERN,
			Blocks.REDSTONE_TORCH,
			Blocks.REDSTONE_WALL_TORCH,
			
			Blocks.CANDLE,
			Blocks.DYED_CANDLE.red(),
			Blocks.DYED_CANDLE.green(),
			Blocks.DYED_CANDLE.blue(),
			Blocks.DYED_CANDLE.orange(),
			Blocks.DYED_CANDLE.cyan(),
			Blocks.DYED_CANDLE.purple(),
			Blocks.DYED_CANDLE.pink(),
			Blocks.DYED_CANDLE.brown(),
			Blocks.DYED_CANDLE.lightBlue(),
			Blocks.DYED_CANDLE.lightGray(),
			Blocks.DYED_CANDLE.gray(),
			Blocks.DYED_CANDLE.black(),
			Blocks.DYED_CANDLE.lime(),
			Blocks.DYED_CANDLE.magenta(),
			Blocks.DYED_CANDLE.yellow(),
			Blocks.DYED_CANDLE.white(),
			
			Blocks.CANDLE_CAKE,
			Blocks.DYED_CANDLE_CAKE.red(),
			Blocks.DYED_CANDLE_CAKE.green(),
			Blocks.DYED_CANDLE_CAKE.blue(),
			Blocks.DYED_CANDLE_CAKE.orange(),
			Blocks.DYED_CANDLE_CAKE.cyan(),
			Blocks.DYED_CANDLE_CAKE.purple(),
			Blocks.DYED_CANDLE_CAKE.pink(),
			Blocks.DYED_CANDLE_CAKE.brown(),
			Blocks.DYED_CANDLE_CAKE.lightBlue(),
			Blocks.DYED_CANDLE_CAKE.lightGray(),
			Blocks.DYED_CANDLE_CAKE.gray(),
			Blocks.DYED_CANDLE_CAKE.black(),
			Blocks.DYED_CANDLE_CAKE.lime(),
			Blocks.DYED_CANDLE_CAKE.magenta(),
			Blocks.DYED_CANDLE_CAKE.yellow(),
			Blocks.DYED_CANDLE_CAKE.white()
	);
	
	public static List<Holder<MobEffect>> NEUTRAL_EFFECTS = List.of(
			MobEffects.GLOWING,
			MobEffects.SLOW_FALLING
	);
	
	public static List<Holder<MobEffect>> POSITIVE_EFFECTS = List.of(
			MobEffects.ABSORPTION,
			MobEffects.RESISTANCE,
			MobEffects.SPEED,
			MobEffects.HASTE,
			MobEffects.STRENGTH,
			MobEffects.INSTANT_HEALTH,
			MobEffects.JUMP_BOOST,
			MobEffects.REGENERATION,
			MobEffects.FIRE_RESISTANCE,
			MobEffects.WATER_BREATHING,
			MobEffects.NIGHT_VISION,
			MobEffects.INVISIBILITY,
			MobEffects.HEALTH_BOOST,
			MobEffects.SATURATION,
			MobEffects.LUCK,
			MobEffects.CONDUIT_POWER,
			MobEffects.DOLPHINS_GRACE,
			MobEffects.HERO_OF_THE_VILLAGE
	);
	
	public static List<Holder<MobEffect>> NEGATIVE_EFFECTS = List.of(
			MobEffects.NAUSEA,
			MobEffects.WEAKNESS,
			MobEffects.BLINDNESS,
			MobEffects.HUNGER,
			MobEffects.SLOWNESS,
			MobEffects.MINING_FATIGUE,
			MobEffects.LEVITATION,
			MobEffects.UNLUCK,
			MobEffects.BAD_OMEN,
			MobEffects.DARKNESS,
			MobEffects.TRIAL_OMEN,
			MobEffects.RAID_OMEN,
			MobEffects.WIND_CHARGED,
			MobEffects.WEAVING,
			MobEffects.OOZING,
			MobEffects.INFESTED
	);
	
	public static List<Holder<MobEffect>> HARMFUL_EFFECTS = List.of(
			MobEffects.INSTANT_DAMAGE,
			MobEffects.WITHER,
			MobEffects.POISON
	);
	
	private static final Random rand = new Random();
	
	public static String chooseRandomFromList(List<String> list) {
		if( list == null || list.isEmpty() ) {
			return list.get(rand.nextInt(list.size()));
		} else {
			return list.get(rand.nextInt(list.size()));
		} // if, else
	}
	
	@SafeVarargs
	public static List<ResourceKey<Biome>> buildRegistryKeyBiomeList(List<ResourceKey<Biome>> primary, List<ResourceKey<Biome>>... secondary ) {
		ArrayList<ResourceKey<Biome>> arrayList = new ArrayList<>(primary);
		for (List<ResourceKey<Biome>> list : secondary) {
			arrayList.addAll( list );
		} // for
		return Collections.unmodifiableList( arrayList );
	}
	
	@SafeVarargs
	public static List<ResourceKey<Structure>> buildRegistryKeyStructureList(List<ResourceKey<Structure>> primary, List<ResourceKey<Structure>>... secondary ) {
		ArrayList<ResourceKey<Structure>> arrayList = new ArrayList<>(primary);
		for (List<ResourceKey<Structure>> list : secondary) {
			arrayList.addAll( list );
		} // for
		return Collections.unmodifiableList( arrayList );
	}
	
	@SafeVarargs
	public static List<String> buildStringList(List<String> primary, List<String>... secondary ) {
		ArrayList<String> arrayList = new ArrayList<>(primary);
		for (List<String> list : secondary) {
			arrayList.addAll( list );
		} // for
		return Collections.unmodifiableList( arrayList );
	}
	
}
